spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/sell?charactorEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson.default-property-inclusion: non_null 属性为null在前端页面被过滤
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##    path: /var/log/tomcat/
#    file: /var/log/tomcat/sell.log
#    level: debug

wechat:
  mpAppId: wxe894cd94e96c24d9
  mpAppSecret: 55c23abfacf4d2ef4ded5e3b24251fb8
